
name: ssh

on:
  workflow_call:
    secrets:
      SSH_PRIVATE_KEY:
        required: true
      COMMAND:
        required: false

jobs:
  ssh:
    name: ssh
    runs-on: ubuntu-latest
    steps:
      - uses: cc332030/ssh-action@main
        timeout-minutes: 2
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          COMMAND: ${{ secrets.COMMAND }}
